//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FILMECRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmeDetalhe
    {
        public int FilmeID { get; set; }
        public string FilmeDescricao { get; set; }
        public Nullable<int> FilmeGeneroID { get; set; }
        public string FilmeNome { get; set; }
    
        public virtual FilmeRefGenero FilmeRefGenero { get; set; }
    }
}
